### ISSUE TITLE
MACC of mobilenet v2 is different from paper

### ISSUE THREAD

**Issue by CuriousCat-7** [sovrasov/flops-counter.pytorch#33]
Hello, thank you for sharing your code. Recently I'm trying to design new architectures based on Mobilenet v2, but I found the Macc calculated by your project is different from it in the paper.

In the [paper](https://arxiv.org/pdf/1801.04381.pdf):
![image](https://user-images.githubusercontent.com/17199271/75547949-06c61e80-5a67-11ea-92cd-c12d984e3797.png)

It should be 585 MMac  and 6.9M paremeters for MobilNet V2(1.4x).
However, 
I get :
- Computational complexity:       610.1 MMac
- Number of parameters:           6.11 M

By the way, I get the different result by [Lyken17's code](https://github.com/Lyken17/pytorch-OpCounter)
- Computational complexity:       603.134720.0 MMac
- Number of parameters:           6.108776.0 M

code I used:
```python
     from torchvision.models import mobilenet_v2
     model = mobilenet_v2(width_mult=1.4)
     from ptflops import get_model_complexity_info
     flops, params = get_model_complexity_info(model, (3,224,224,), as_strings=True, print_per_layer_stat=True,)
     print('{:<30}  {:<8}'.format('Computational complexity: ', flops))
     print('{:<30}  {:<8}'.format('Number of parameters: ', params))
```
Could you tell me the reason for the difference? Thanks.

**Comment by sovrasov** [comment]
The original MobileNet V2 is implemented in TensorFlow. TF has it's own routines to calculate flops and parameters. You use a re-implementation of MN V2 in pytorch, and there can exist some differences in both implementation and counting procedures.

The difference with THOP in the number of parameters is caused by rounding. If you turn the `as_strings` flag to false you'll get the exact number. THOP doesn't take into account activations and BNs, but ptflops does, thus, it outputs bigger number of flops than THOP.

**Comment by CuriousCat-7** [comment]
> The original MobileNet V2 is implemented in TensorFlow. TF has it's own routines to calculate flops and parameters. You use a re-implementation of MN V2 in pytorch, and there can exist some differences in both implementation and counting procedures.
> 
> The difference with THOP in the number of parameters is caused by rounding. If you turn the `as_strings` flag to false you'll get the exact number. THOP doesn't take into account activations and BNs, but ptflops does, thus, it outputs bigger number of flops than THOP.

Thank you for your detailed reply, I will close this issue because the problem has been solved
