### ISSUE TITLE
Warning: module xxx is treated as a zero-op.

### ISSUE THREAD

**Issue by likyoo** [sovrasov/flops-counter.pytorch#52]

**Comment by sovrasov** [comment]
Hi! Generally these warnings are expected, because currently I don't see any way how to discriminate a true unknown operation from a custom module-container. Warnings are useful to check whether you have unfamiliar for ptflops modules. If you see warnings only on modules, that are not endpoint operations by design and just contain other modules, then it's all ok.

**Comment by likyoo** [comment]
thanks!
